name: ContextPR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  contextpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run ContextPR
        uses: Marian2910/context-pr@main
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: https://sonarcloud.io
          sonar-organization: ${{ secrets.SONAR_ORGANIZATION }}
          sonar-project-key: ${{ secrets.PROJECT_KEY }}
          pr-number: ${{ github.event.pull_request.number }}
          github-repository: ${{ github.repository }}
          dry-run: "true"
